(function(){
  const state = { modal: null, map: null, layer: null, activeWindow: '3d', currentClusterId: null, miniMaps: new Map(), miniMapHandlers: new WeakSet() };

  function escapeHtml(s){ return String(s ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch])); }
  function ensureLeaflet(){ return !!(window.L && typeof window.L.map === 'function'); }
  function parseDate(s){ const t = Date.parse(s || ''); return Number.isFinite(t) ? t : 0; }
  function hoursForWindow(win){ return win === '7d' ? 168 : (win === '24h' ? 24 : 72); }
  function getItemTs(item){ return parseDate(item?.latest_published_at) || parseDate(item?.updated_at) || parseDate(item?.created_at) || 0; }
  function getFeedItems(){ return Array.isArray(window.__checkneFeedItems) ? window.__checkneFeedItems : []; }
  function normalizeLocation(item){
    const loc = item?.map_location;
    if (!loc || typeof loc !== 'object') return null;
    const lat = Number(loc.lat), lng = Number(loc.lon ?? loc.lng);
    if (!Number.isFinite(lat) || !Number.isFinite(lng)) return null;
    return { lat, lng, label: String(loc.label || 'Mapped location'), kind: String(loc.kind || 'point') };
  }
  function getScore(item){ return Number(item?.credibility_score ?? item?.credibility ?? item?.score ?? item?.rating ?? 0) || 0; }
  function buildDataset(win){
    const now = Date.now(); const maxAge = hoursForWindow(win) * 3600 * 1000;
    return getFeedItems().filter(Boolean).filter(it => getScore(it) > 70).filter(it => normalizeLocation(it)).filter(it => { const ts = getItemTs(it); return !ts || (now - ts) <= maxAge; });
  }
  function groupKey(loc){ return `${loc.label}|${loc.lat.toFixed(2)}|${loc.lng.toFixed(2)}`; }
  function groupItems(items){ const map = new Map(); for (const item of items){ const loc = normalizeLocation(item); if (!loc) continue; const key = groupKey(loc); if (!map.has(key)) map.set(key, { loc, items: [] }); map.get(key).items.push(item);} return Array.from(map.values()).sort((a,b)=>b.items.length-a.items.length); }
  function firstImage(group){ for (const it of group.items){ const src = it?.image || it?.thumbnail || it?.thumb || it?.image_url || it?.imageUrl; if (src) return String(src); } return ''; }
  function markerHtml(group, options = {}){ const img = firstImage(group); const count = group.items.length; const cls = options.compact ? ' compact' : ''; return `<div class="eventMapMarker${count>1 ? ' hasCount' : ''}${cls}">${img ? `<img src="${escapeHtml(img)}" alt="" loading="lazy" draggable="false" />` : `<div class="eventMapMarkerFallback">${escapeHtml((group.loc.label||'•').charAt(0).toUpperCase())}</div>`}${count > 1 ? `<span class="eventMapMarkerCount">${count}</span>` : ''}</div>`; }
  function popupHtml(group){ const title = `${group.items.length} mapped stor${group.items.length === 1 ? 'y' : 'ies'}`; const rows = group.items.map((it) => { const cid = Number(it?.cluster_id ?? it?.event_id ?? 0); const rawTitle = String(it?.title || 'Event'); return `<li><a href="#" class="eventMapStoryLink" data-story-cluster-id="${cid}" data-story-title="${escapeHtml(rawTitle)}">${escapeHtml(rawTitle)}</a></li>`; }).join(''); return `<div class="eventMapPopup"><div class="eventMapPopupHead"><div class="eventMapPopupTitle">${escapeHtml(title)}</div></div><div class="eventMapPopupSub">${escapeHtml(group.loc.label || '')}</div><ul class="eventMapPopupList">${rows}</ul></div>`; }
  function wirePopupStoryLinks(container){ if (!container || container.__eventMapWired) return; container.__eventMapWired = true; container.addEventListener('click', (e) => { const storyBtn = e.target.closest('.eventMapStoryLink'); if (!storyBtn) return; e.preventDefault(); e.stopPropagation(); fillSearchWithStory(storyBtn.getAttribute('data-story-title') || storyBtn.textContent || ''); }); }
  function clearMap(){ if (state.layer) { try { state.layer.clearLayers(); } catch(_) {} } }
  function updateCount(items, groups){ const el = document.getElementById('eventMapMeta'); if (!el) return; el.textContent = `${items.length} mapped stories · ${groups.length} locations`; }
  function renderFullMap(){ if (!state.map || !ensureLeaflet()) return; const items = buildDataset(state.activeWindow); const groups = groupItems(items); updateCount(items, groups); clearMap(); if (!groups.length) return; const bounds = []; for (const group of groups){ const html = markerHtml(group); const icon = L.divIcon({ html, className: 'eventMapMarkerWrap', iconSize: [64, 64], iconAnchor: [32, 32], popupAnchor: [0, -24] }); const marker = L.marker([group.loc.lat, group.loc.lng], { icon }); marker.bindPopup(popupHtml(group), { maxWidth: 340, className: 'eventMapLeafletPopup' }); marker.on('popupopen', (ev) => { try { wirePopupStoryLinks(ev.popup && ev.popup.getElement ? ev.popup.getElement() : null); } catch(_){} }); state.layer.addLayer(marker); bounds.push([group.loc.lat, group.loc.lng]); } if (bounds.length === 1) state.map.setView(bounds[0], 4); else state.map.fitBounds(bounds, { padding: [30, 30] }); }
  function ensureModalMap(){ const host = document.getElementById('eventMapCanvas'); if (!host || !ensureLeaflet()) return null; if (!state.map){ state.map = L.map(host, { zoomControl: true, worldCopyJump: true }); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18, attribution: '&copy; OpenStreetMap contributors' }).addTo(state.map); state.layer = L.layerGroup().addTo(state.map);} return state.map; }
  function fillSearchWithStory(storyTitle){ closeModal(); const title = String(storyTitle || '').trim(); const searchEl = document.getElementById('search'); try { window.scrollTo({ top: 0, behavior: 'smooth' }); } catch(_){} if (!searchEl || !title) return; searchEl.value = title; try { if (window.state) { window.state.q = title; window.state.topicQ = ''; window.state.topicQs = []; } } catch(_){} searchEl.dispatchEvent(new Event('input', { bubbles: true })); searchEl.dispatchEvent(new Event('change', { bubbles: true })); setTimeout(() => { try { searchEl.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true })); } catch(_){} }, 25); }
  function openModal(clusterId){ state.currentClusterId = clusterId || null; state.modal = document.getElementById('eventMapModal'); if (!state.modal) return; state.modal.classList.add('isOpen'); document.body.classList.add('eventMapModalOpen'); ensureModalMap(); setTimeout(() => { try { state.map.invalidateSize(); } catch(_){} renderFullMap(); }, 40); }
  function closeModal(){ const modal = document.getElementById('eventMapModal'); if (!modal) return; modal.classList.remove('isOpen'); document.body.classList.remove('eventMapModalOpen'); }
  function wireModal(){ const modal = document.getElementById('eventMapModal'); if (!modal) return; modal.addEventListener('click', (e) => { const close = e.target.closest('[data-event-map-close="1"]'); if (close) { closeModal(); return; } const winBtn = e.target.closest('[data-map-window]'); if (winBtn){ state.activeWindow = String(winBtn.getAttribute('data-map-window') || '3d'); modal.querySelectorAll('[data-map-window]').forEach(btn => btn.classList.toggle('isOn', btn === winBtn)); renderFullMap(); return; } const storyBtn = e.target.closest('.eventMapStoryLink'); if (storyBtn){ e.preventDefault(); fillSearchWithStory(storyBtn.getAttribute('data-story-title') || storyBtn.textContent || ''); } }); }
  function renderMiniMap(host, item){ if (!host || state.miniMaps.has(host)) return; const loc = normalizeLocation(item); if (!loc || !ensureLeaflet() || getScore(item) <= 70) { host.textContent = 'No mapped location yet.'; return; } const map = L.map(host, { zoomControl: true, attributionControl: false, dragging: true, scrollWheelZoom: false, doubleClickZoom: false, boxZoom: false, keyboard: false, tap: true, touchZoom: true }); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18 }).addTo(map); const single = { loc, items: [item] }; const icon = L.divIcon({ html: markerHtml(single, { compact: true }), className: 'eventMapMarkerWrap', iconSize: [44, 44], iconAnchor: [22, 22] }); const marker = L.marker([loc.lat, loc.lng], { icon }).addTo(map); marker.on('click', () => { const cid = Number(item?.cluster_id ?? item?.event_id ?? 0); if (cid) openModal(cid); }); map.setView([loc.lat, loc.lng], loc.kind === 'city' ? 6 : 4); host.style.cursor = 'grab'; host.addEventListener('dblclick', () => { const cid = Number(item?.cluster_id ?? item?.event_id ?? 0); if (cid) openModal(cid); }); state.miniMaps.set(host, map); setTimeout(() => { try { map.invalidateSize(); } catch(_){} }, 60); }
  function bootMiniMaps(){ document.querySelectorAll('.eventMapMini').forEach((host) => { if (state.miniMaps.has(host)) return; const cid = Number(host.getAttribute('data-cluster-id') || 0); const item = getFeedItems().find(it => Number(it?.cluster_id ?? it?.event_id ?? 0) === cid); if (item) renderMiniMap(host, item); }); }
  function wireButtons(){ document.addEventListener('click', (e) => { const btn = e.target.closest('[data-open-full-map]'); if (btn){ const cid = Number(btn.getAttribute('data-open-full-map') || 0); openModal(cid); return; } const storyBtn = e.target.closest('.eventMapStoryLink'); if (storyBtn){ e.preventDefault(); e.stopPropagation(); fillSearchWithStory(storyBtn.getAttribute('data-story-title') || storyBtn.textContent || ''); } }); }
  document.addEventListener('DOMContentLoaded', () => { wireButtons(); wireModal(); bootMiniMaps(); });
  document.addEventListener('checkne:feedItemsUpdated', () => { setTimeout(bootMiniMaps, 0); if (document.getElementById('eventMapModal')?.classList.contains('isOpen')) renderFullMap(); });
  document.addEventListener('keydown', (e) => { if (e.key === 'Escape') closeModal(); });
})();